server:
  port: 8083

spring:
#  application:
#    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/order
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # Add this here
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  datasource:
#    url: jdbc:h2:file:C:/Users/chira/test;AUTO_SERVER=TRUE # in-memory default DB
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#      hibernate:
#        ddl-auto: update            # auto-create/update tables               # show SQL in console
#  h2:
#      console:
#        enabled: true               # enable H2 web console
#        path: /h2-console           # access at http://localhost:8080/h2-console
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

