server:
  port: 8084
spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888
#  cloud:
#    gateway:
#      routes:
#        - id: product-services
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/v1/products/**
#        - id: user-services
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/v1/users/**
#        - id: order-services
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/v1/orders/**
#            - Path=/api/v1/cart/**
#        - id: eureka-server
#          uri: http://localhost:8761
#          predicates:
#              - Path=/eureka/main
#          filters:
#            - SetPath=/
#        - id: eureka-server-static
#          uri: http://localhost:8761
#          predicates:
#              - Path=/eureka/**

        




