server:
  port: 8084
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: product-services
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**
        - id: user-services
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/users/**
        - id: order-services
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/orders/** , /api/v1/cart/**




