server:
  port: 8081

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/productservice
    username: root
    password: Chirayu@1911
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect-platform: org.hibernate.dialect.MySQLDialect # Add this here






#  datasource:
#    url: jdbc:h2:file:C:/Users/chira/test;AUTO_SERVER=TRUE # in-memory default DB
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update            # auto-create/update tables               # show SQL in console
#  h2:
#     console:
#        enabled: true               # enable H2 web console
#        path: /h2-console           # access at http://localhost:8080/h2-console

