server:
  port: 8081

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5433/product
    username: chirayu
    password: chirayu
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect-platform: org.hibernate.dialect.POSTGRESQLDialect # Add this here

#  datasource:
#    url: jdbc:h2:file:C:/Users/chira/test;AUTO_SERVER=TRUE # in-memory default DB
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update            # auto-create/update tables               # show SQL in console
#  h2:
#     console:
#        enabled: true               # enable H2 web console
#        path: /h2-console           # access at http://localhost:8080/h2-console

