server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:file:C:/Users/chira/test;AUTO_SERVER=TRUE # in-memory default DB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
      hibernate:
        ddl-auto: update            # auto-create/update tables               # show SQL in console
  h2:
      console:
        enabled: true               # enable H2 web console
        path: /h2-console           # access at http://localhost:8080/h2-console


